package org.zhd.crm.server.repository.statistic

import org.springframework.data.domain.Page
import org.springframework.data.domain.Pageable
import org.springframework.data.jpa.repository.Query
import org.springframework.data.repository.CrudRepository
import org.zhd.crm.server.model.statistic.GoodsSales
import java.sql.Timestamp

interface GoodsSalesRepository : CrudRepository<GoodsSales, Long> {
    @Query(value = "from GoodsSales gs where gs.memberCode = ?1 and gs.dealDate between ?2 and ?3 and (gs.category = ?4 or ?4 is null) order by gs.updateAt desc")
    fun findList(memCode: String, startTime: Timestamp, endTime: Timestamp, category: String?): List<GoodsSales>

    @Query(value = "from GoodsSales gs where gs.memberCode=?1 and to_char(gs.dealDate, 'yyyy-MM-dd') = ?2 and gs.type=?3 and gs.category=?4")
    fun findGoodSale(memCode: String, dealDate: String, type: Int, category: String): GoodsSales?

    @Query(value = "select gs.category from GoodsSales gs where gs.memberCode = ?1 group by gs.category")
    fun goodsType(memCode: String): List<String>

    @Query(value = "select COALESCE(sum(gs.weight),0.0) from GoodsSales gs where gs.memberCode=?1 and to_char(gs.dealDate, 'YYYY-MM-DD')=?2 and gs.type=?3")
    fun sumWeight(memCode: String, dealDate: String, type: Int): Double

    @Query(value = "select COALESCE(sum(gs.weight),0.0) from GoodsSales gs where gs.memberCode=?1 and to_char(gs.dealDate, 'YYYY-MM-DD hh24:mi:ss')<=?2 and gs.type=?3")
    fun sumTotalWeight(memCode: String, dealDate: String, type: Int): Double

    @Query(value = "select distinct(gs.category) from GoodsSales gs where gs.memberCode=?1")
    fun distinctGoods(memCode: String): List<String>

    @Query(value = "select distinct gs.category from GoodsSales gs where gs.category not in (?1)")
    fun findSupplyCatalog(list: List<String>): List<String>

    // 对于聚合函数,如果使用#pageable不能识别正确的别名，比如sum(XX) as AA想要的是order by AA,结果报错：order by a.AA,a.AA不存在,所以这边分开写
    @Query(nativeQuery = true, countQuery = "select count(*) from v_demission_sales_list a where (a.comp_name like %?1% or ?1 is null) and (a.acct_name like %?2% or ?2 is null) and (a.dpt_name like %?3% or ?3 is null) and (to_char(a.fk_acct_id) = ?4 or ?4 is null) and (to_char(a.fk_dpt_id) = ?5 or ?5 is null) and (to_char(a.fk_org_id) = ?6 or ?6 is null) group by a.comp_name,a.acct_name,a.dpt_name order by ?#{#pageable}", value = "select a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where (a.comp_name like %?1% or ?1 is null) and (a.acct_name like %?2% or ?2 is null) and (a.dpt_name like %?3% or ?3 is null) and (to_char(a.fk_acct_id) = ?4 or ?4 is null) and (to_char(a.fk_dpt_id) = ?5 or ?5 is null) and (to_char(a.fk_org_id) = ?6 or ?6 is null) group by a.comp_name,a.acct_name,a.dpt_name order by ?#{#pageable},weight desc")
    fun findFirstSortStat(compName: String?, acctName: String?, dptName: String?, id: String?, dptId: String?, orgId: String?, pageable: Pageable): Page<Any>

    @Query(nativeQuery = true, countQuery = "select count(*) from v_demission_sales_list a where (a.comp_name like %?1% or ?1 is null) and (a.acct_name like %?2% or ?2 is null) and (a.dpt_name like %?3% or ?3 is null) and (to_char(a.fk_acct_id) = ?4 or ?4 is null) and (to_char(a.fk_dpt_id) = ?5 or ?5 is null) and (to_char(a.fk_org_id) = ?6 or ?6 is null) group by a.comp_name,a.acct_name,a.dpt_name order by ?#{#pageable}", value = "select a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where (a.comp_name like %?1% or ?1 is null) and (a.acct_name like %?2% or ?2 is null) and (a.dpt_name like %?3% or ?3 is null) and (to_char(a.fk_acct_id) = ?4 or ?4 is null) and (to_char(a.fk_dpt_id) = ?5 or ?5 is null) and (to_char(a.fk_org_id) = ?6 or ?6 is null) group by a.comp_name,a.acct_name,a.dpt_name order by ?#{#pageable},weight asc")
    fun findSecondSortStat(compName: String?, acctName: String?, dptName: String?, id: String?, dptId: String?, orgId: String?, pageable: Pageable): Page<Any>

    @Query(nativeQuery = true, countQuery = "select count(*) from v_demission_sales_list a where (a.comp_name like %?1% or ?1 is null) and (a.acct_name like %?2% or ?2 is null) and (a.dpt_name like %?3% or ?3 is null) and (to_char(a.fk_acct_id) = ?4 or ?4 is null) and (to_char(a.fk_dpt_id) = ?5 or ?5 is null) and (to_char(a.fk_org_id) = ?6 or ?6 is null) group by a.comp_name,a.acct_name,a.dpt_name order by ?#{#pageable}", value = "select a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where (a.comp_name like %?1% or ?1 is null) and (a.acct_name like %?2% or ?2 is null) and (a.dpt_name like %?3% or ?3 is null) and (to_char(a.fk_acct_id) = ?4 or ?4 is null) and (to_char(a.fk_dpt_id) = ?5 or ?5 is null) and (to_char(a.fk_org_id) = ?6 or ?6 is null) group by a.comp_name,a.acct_name,a.dpt_name order by ?#{#pageable},high_sell desc")
    fun findThirdSortStat(compName: String?, acctName: String?, dptName: String?, id: String?, dptId: String?, orgId: String?, pageable: Pageable): Page<Any>

    @Query(nativeQuery = true, countQuery = "select count(*) from v_demission_sales_list a where (a.comp_name like %?1% or ?1 is null) and (a.acct_name like %?2% or ?2 is null) and (a.dpt_name like %?3% or ?3 is null) and (to_char(a.fk_acct_id) = ?4 or ?4 is null) and (to_char(a.fk_dpt_id) = ?5 or ?5 is null) and (to_char(a.fk_org_id) = ?6 or ?6 is null) group by a.comp_name,a.acct_name,a.dpt_name order by ?#{#pageable}", value = "select a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where (a.comp_name like %?1% or ?1 is null) and (a.acct_name like %?2% or ?2 is null) and (a.dpt_name like %?3% or ?3 is null) and (to_char(a.fk_acct_id) = ?4 or ?4 is null) and (to_char(a.fk_dpt_id) = ?5 or ?5 is null) and (to_char(a.fk_org_id) = ?6 or ?6 is null) group by a.comp_name,a.acct_name,a.dpt_name order by ?#{#pageable},high_sell asc")
    fun findFourthSortStat(compName: String?, acctName: String?, dptName: String?, id: String?, dptId: String?, orgId: String?, pageable: Pageable): Page<Any>

    @Query(nativeQuery = true, countQuery = "select count(*) from (select to_char(a.profit_date,'yyyy-MM') as dateList,a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where a.comp_name = ?3 and a.acct_name = ?4 and a.dpt_name = ?5 group by to_char(a.profit_date,'yyyy-MM'),a.comp_name,a.acct_name,a.dpt_name) aa where (aa.dateList >= ?1 or ?1 is null) and (aa.dateList <= ?2 or ?2 is null) order by ?#{#pageable}", value = "select * from (select to_char(a.profit_date,'yyyy-MM') as dateList,a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where a.comp_name = ?3 and a.acct_name = ?4 and a.dpt_name = ?5 group by to_char(a.profit_date,'yyyy-MM'),a.comp_name,a.acct_name,a.dpt_name) aa where (aa.dateList >= ?1 or ?1 is null) and (aa.dateList <= ?2 or ?2 is null) order by ?#{#pageable},dateList asc")
    fun findFirstSortDetails(startTime: String?, endTime: String?, compName: String, acctName: String, dptName: String, pageable: Pageable): Page<Any>

    @Query(nativeQuery = true, countQuery = "select count(*) from (select to_char(a.profit_date,'yyyy-MM') as dateList,a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where a.comp_name = ?3 and a.acct_name = ?4 and a.dpt_name = ?5 group by to_char(a.profit_date,'yyyy-MM'),a.comp_name,a.acct_name,a.dpt_name) aa where (aa.dateList >= ?1 or ?1 is null) and (aa.dateList <= ?2 or ?2 is null) order by ?#{#pageable}", value = "select * from (select to_char(a.profit_date,'yyyy-MM') as dateList,a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where a.comp_name = ?3 and a.acct_name = ?4 and a.dpt_name = ?5 group by to_char(a.profit_date,'yyyy-MM'),a.comp_name,a.acct_name,a.dpt_name) aa where (aa.dateList >= ?1 or ?1 is null) and (aa.dateList <= ?2 or ?2 is null) order by ?#{#pageable},weight desc")
    fun findSecondSortDetails(startTime: String?, endTime: String?, compName: String, acctName: String, dptName: String, pageable: Pageable): Page<Any>

    @Query(nativeQuery = true, countQuery = "select count(*) from (select to_char(a.profit_date,'yyyy-MM') as dateList,a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where a.comp_name = ?3 and a.acct_name = ?4 and a.dpt_name = ?5 group by to_char(a.profit_date,'yyyy-MM'),a.comp_name,a.acct_name,a.dpt_name) aa where (aa.dateList >= ?1 or ?1 is null) and (aa.dateList <= ?2 or ?2 is null) order by ?#{#pageable}", value = "select * from (select to_char(a.profit_date,'yyyy-MM') as dateList,a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where a.comp_name = ?3 and a.acct_name = ?4 and a.dpt_name = ?5 group by to_char(a.profit_date,'yyyy-MM'),a.comp_name,a.acct_name,a.dpt_name) aa where (aa.dateList >= ?1 or ?1 is null) and (aa.dateList <= ?2 or ?2 is null) order by ?#{#pageable},weight asc")
    fun findThirdSortDetails(startTime: String?, endTime: String?, compName: String, acctName: String, dptName: String, pageable: Pageable): Page<Any>

    @Query(nativeQuery = true, countQuery = "select count(*) from (select to_char(a.profit_date,'yyyy-MM') as dateList,a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where a.comp_name = ?3 and a.acct_name = ?4 and a.dpt_name = ?5 group by to_char(a.profit_date,'yyyy-MM'),a.comp_name,a.acct_name,a.dpt_name) aa where (aa.dateList >= ?1 or ?1 is null) and (aa.dateList <= ?2 or ?2 is null) order by ?#{#pageable}", value = "select * from (select to_char(a.profit_date,'yyyy-MM') as dateList,a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where a.comp_name = ?3 and a.acct_name = ?4 and a.dpt_name = ?5 group by to_char(a.profit_date,'yyyy-MM'),a.comp_name,a.acct_name,a.dpt_name) aa where (aa.dateList >= ?1 or ?1 is null) and (aa.dateList <= ?2 or ?2 is null) order by ?#{#pageable},high_sell desc")
    fun findFourthSortDetails(startTime: String?, endTime: String?, compName: String, acctName: String, dptName: String, pageable: Pageable): Page<Any>

    @Query(nativeQuery = true, countQuery = "select count(*) from (select to_char(a.profit_date,'yyyy-MM') as dateList,a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where a.comp_name = ?3 and a.acct_name = ?4 and a.dpt_name = ?5 group by to_char(a.profit_date,'yyyy-MM'),a.comp_name,a.acct_name,a.dpt_name) aa where (aa.dateList >= ?1 or ?1 is null) and (aa.dateList <= ?2 or ?2 is null) order by ?#{#pageable}", value = "select * from (select to_char(a.profit_date,'yyyy-MM') as dateList,a.comp_name,a.acct_name,a.dpt_name,sum(a.data_bweight) as weight,sum(a.gm) as high_sell from v_demission_sales_list a where a.comp_name = ?3 and a.acct_name = ?4 and a.dpt_name = ?5 group by to_char(a.profit_date,'yyyy-MM'),a.comp_name,a.acct_name,a.dpt_name) aa where (aa.dateList >= ?1 or ?1 is null) and (aa.dateList <= ?2 or ?2 is null) order by ?#{#pageable},high_sell asc")
    fun findFifthSortDetails(startTime: String?, endTime: String?, compName: String, acctName: String, dptName: String, pageable: Pageable): Page<Any>

    @Query(nativeQuery = true, countQuery = "select count(*) from (select a.sumgoods_batch,a.partsname_name,a.goods_material,a.goods_spec,a.goods_property1,a.productarea_name,a.goods_property5,a.goods_property4 from erp_forbi_xs a,v_erpcstm_basicinfo_list@CRMSTAT_CRM b where a.customer_code = b.erp_code and (to_char(b.acctId) = ?1 or ?1 is null) and (to_char(b.dptId) = ?2 or ?2 is null) and (to_char(b.orgId) = ?3 or ?3 is null) and (instr(a.partsname_name,?4)>0 or ?4 is null) and (instr(a.goods_material,?5)>0 or ?5 is null) and (instr(a.goods_spec,?6)>0 or ?6 is null) and (instr(a.goods_property1,?7)>0 or ?7 is null) and (instr(a.goods_property5,?8)>0 or ?8 is null) and (instr(a.goods_property4,?9)>0 or ?9 is null) group by a.sumgoods_batch,a.partsname_name,a.goods_material,a.goods_spec,a.goods_property1,a.productarea_name,a.goods_property5,a.goods_property4 order by ?#{#pageable})", value = "select a.sumgoods_batch,a.partsname_name,a.goods_material,a.goods_spec,a.goods_property1,a.productarea_name,a.goods_property5,a.goods_property4,count(distinct a.customer_code) from erp_forbi_xs a,v_erpcstm_basicinfo_list@crmstat_crm b where a.customer_code = b.erp_code and (to_char(b.acctId) = ?1 or ?1 is null) and (to_char(b.dptId) = ?2 or ?2 is null) and (to_char(b.orgId) = ?3 or ?3 is null) and (instr(a.partsname_name,?4)>0 or ?4 is null) and (instr(a.goods_material,?5)>0 or ?5 is null) and (instr(a.goods_spec,?6)>0 or ?6 is null) and (instr(a.goods_property1,?7)>0 or ?7 is null) and (instr(a.goods_property5,?8)>0 or ?8 is null) and (instr(a.goods_property4,?9)>0 or ?9 is null) group by a.sumgoods_batch,a.partsname_name,a.goods_material,a.goods_spec,a.goods_property1,a.productarea_name,a.goods_property5,a.goods_property4 order by ?#{#pageable},count(distinct a.customer_code) desc")
    fun findFirstSortSales(acctId: String?, dptId: String?, orgId: String?, partsName: String?, material: String?, goodsSpec: String?, length: String?, toleranceRange: String?, weightRange: String?, pageable: Pageable): Page<Any>

    @Query(nativeQuery = true, countQuery = "select count(*) from (select a.sumgoods_batch,a.partsname_name,a.goods_material,a.goods_spec,a.goods_property1,a.productarea_name,a.goods_property5,a.goods_property4 from erp_forbi_xs a,v_erpcstm_basicinfo_list@CRMSTAT_CRM b where a.customer_code = b.erp_code and (to_char(b.acctId) = ?1 or ?1 is null) and (to_char(b.dptId) = ?2 or ?2 is null) and (to_char(b.orgId) = ?3 or ?3 is null) and (instr(a.partsname_name,?4)>0 or ?4 is null) and (instr(a.goods_material,?5)>0 or ?5 is null) and (instr(a.goods_spec,?6)>0 or ?6 is null) and (instr(a.goods_property1,?7)>0 or ?7 is null) and (instr(a.goods_property5,?8)>0 or ?8 is null) and (instr(a.goods_property4,?9)>0 or ?9 is null) group by a.sumgoods_batch,a.partsname_name,a.goods_material,a.goods_spec,a.goods_property1,a.productarea_name,a.goods_property5,a.goods_property4 order by ?#{#pageable})", value = "select a.sumgoods_batch,a.partsname_name,a.goods_material,a.goods_spec,a.goods_property1,a.productarea_name,a.goods_property5,a.goods_property4,count(distinct a.customer_code) from erp_forbi_xs a,v_erpcstm_basicinfo_list@crmstat_crm b where a.customer_code = b.erp_code and (to_char(b.acctId) = ?1 or ?1 is null) and (to_char(b.dptId) = ?2 or ?2 is null) and (to_char(b.orgId) = ?3 or ?3 is null) and (instr(a.partsname_name,?4)>0 or ?4 is null) and (instr(a.goods_material,?5)>0 or ?5 is null) and (instr(a.goods_spec,?6)>0 or ?6 is null) and (instr(a.goods_property1,?7)>0 or ?7 is null) and (instr(a.goods_property5,?8)>0 or ?8 is null) and (instr(a.goods_property4,?9)>0 or ?9 is null) group by a.sumgoods_batch,a.partsname_name,a.goods_material,a.goods_spec,a.goods_property1,a.productarea_name,a.goods_property5,a.goods_property4 order by ?#{#pageable},count(distinct a.customer_code) asc")
    fun findSecondSortSales(acctId: String?, dptId: String?, orgId: String?, partsName: String?, material: String?, goodsSpec: String?, length: String?, toleranceRange: String?, weightRange: String?, pageable: Pageable): Page<Any>

//    @Query(nativeQuery = true, countQuery = "select count(*) from (select a.sumgoods_batch,b.comp_name,b.dptName,b.acctName,b.linkName,b.phone,COALESCE(sum(a.data_bweight),0.0) from erp_forbi_xs a,v_erpcstm_basicinfo_list@crmdev b where a.customer_code = b.erp_code and (to_char(b.acctId) = ?1 or ?1 is null) and (to_char(b.dptId) = ?2 or ?2 is null) and (to_char(b.orgId) = ?3 or ?3 is null) and a.sumgoods_batch = ?4 and (b.comp_name like %?5% or ?5 is null) and (b.dptName like %?6% or ?6 is null) and (b.acctName like %?7% or ?7 is null) group by a.sumgoods_batch,b.comp_name,b.dptName,b.acctName,b.linkName,b.phone order by ?#{#pageable})", value = "select a.sumgoods_batch,b.comp_name,b.dptName,b.acctName,b.linkName,b.phone,COALESCE(sum(a.data_bweight),0.0) from erp_forbi_xs a,v_erpcstm_basicinfo_list@crmdev b where a.customer_code = b.erp_code and (to_char(b.acctId) = ?1 or ?1 is null) and (to_char(b.dptId) = ?2 or ?2 is null) and (to_char(b.orgId) = ?3 or ?3 is null) and a.sumgoods_batch = ?4 and (b.comp_name like %?5% or ?5 is null) and (b.dptName like %?6% or ?6 is null) and (b.acctName like %?7% or ?7 is null) group by a.sumgoods_batch,b.comp_name,b.dptName,b.acctName,b.linkName,b.phone order by ?#{#pageable},COALESCE(sum(a.data_bweight),0.0) desc")
//    fun findFstSrtCstmSales(acctId: String?, dptId: String?, orgId: String?, sumgoodsBatch: String, compName: String?, dptName: String?, acctName: String?, pageable: Pageable): Page<Any>
//
//    @Query(nativeQuery = true, countQuery = "select count(*) from (select a.sumgoods_batch,b.comp_name,b.dptName,b.acctName,b.linkName,b.phone,COALESCE(sum(a.data_bweight),0.0) from erp_forbi_xs a,v_erpcstm_basicinfo_list@crmdev b where a.customer_code = b.erp_code and (to_char(b.acctId) = ?1 or ?1 is null) and (to_char(b.dptId) = ?2 or ?2 is null) and (to_char(b.orgId) = ?3 or ?3 is null) and a.sumgoods_batch = ?4 and (b.comp_name like %?5% or ?5 is null) and (b.dptName like %?6% or ?6 is null) and (b.acctName like %?7% or ?7 is null) group by a.sumgoods_batch,b.comp_name,b.dptName,b.acctName,b.linkName,b.phone order by ?#{#pageable})", value = "select a.sumgoods_batch,b.comp_name,b.dptName,b.acctName,b.linkName,b.phone,COALESCE(sum(a.data_bweight),0.0) from erp_forbi_xs a,v_erpcstm_basicinfo_list@crmdev b where a.customer_code = b.erp_code and (to_char(b.acctId) = ?1 or ?1 is null) and (to_char(b.dptId) = ?2 or ?2 is null) and (to_char(b.orgId) = ?3 or ?3 is null) and a.sumgoods_batch = ?4 and (b.comp_name like %?5% or ?5 is null) and (b.dptName like %?6% or ?6 is null) and (b.acctName like %?7% or ?7 is null) group by a.sumgoods_batch,b.comp_name,b.dptName,b.acctName,b.linkName,b.phone order by ?#{#pageable},COALESCE(sum(a.data_bweight),0.0) asc")
//    fun findScdSrtCstmSales(acctId: String?, dptId: String?, orgId: String?, sumgoodsBatch: String, compName: String?, dptName: String?, acctName: String?, pageable: Pageable): Page<Any>
}