package org.zhd.crm.server.model.projection

interface BehaviorProjection {//jpa Projection,按顺序的，和别名没关系
    fun getIp(): String
    fun getIpLocation(): String
    fun getUserId(): String
    fun getUserName(): String
    fun getEmp(): String
    fun getGoodsName(): String
    fun getSupply(): String
    fun getMaterial(): String
    fun getStandard(): String
    fun getSearch(): String
    fun getWarehouse(): String
    fun getToleranceStart(): String
    fun getToleranceEnd(): String
    fun getOrderId(): String
    fun getToleranceRange(): String
    fun getWeightRange(): String
    fun getAmount(): String
    fun getWeight(): String
    fun getOrderNo(): String
    fun getDiff(): Double
    fun getDealFrom(): String
    fun getType(): String
    fun getDeploy(): String
    fun getCarryNo(): String
    fun getMoney(): Double
    fun getPriority(): String
    fun getContractNo(): String
    fun getMphone(): String
    fun getNickName(): String
    fun getDitchWay(): String
    fun getStartArea(): String
    fun getEndArea(): String
    fun getNum(): Double
    fun getIsSpecialOffer(): String
    fun getIsNewProduct(): String
    fun getLength(): String
    fun getLjPrice(): Double
    fun getBjPrice(): Double
    fun getMinPrice(): Double
    fun getSellType(): String
    fun getCategoryName(): String
    fun getMinWeight(): Double
    fun getPercentage(): String
    fun getRegion(): String
    fun getDateRange(): String
    fun getStatus(): String
    fun getMeasure(): String
    fun getTime(): Long
    fun getSource(): String
    fun getEvent(): String
    fun getEventEn(): String
    fun getId(): String
}